#!/usr/bin/python3
"""multiplies2matricesbyusingthemoduleNumPy"""
deflazy_matrix_mul(m_a,m_b):
"""
Returnstheprodofmultiplying2matrices
Args:
m_a:firstmatrix
m_b:secondmatrix
"""
return(np.matmul(m_a,m_b))
