importctypes

lib=ctypes.CDLL('./libPython.so')
lib.print_python_string.argtypes=[ctypes.py_object]
s="Thespoondoesnotexist"
lib.print_python_string(s)
s="ложканесуществует"
lib.print_python_string(s)
s="Lacuillèren'existepas"
lib.print_python_string(s)
s="勺子不存在"
lib.print_python_string(s)
s="숟가락은존재하지않는다."
lib.print_python_string(s)
s="スプーンは存在しない"
lib.print_python_string(s)
s=b"Thespoondoesnotexist"
lib.print_python_string(s)
julien@ubuntu:~/0x07.PyhtonStrings$gcc-shared-Wl,-soname,libPython.so-olibPython.so-fPIC-I/usr/include/python3.4102-python.c
