#!/usr/bin/python3
"""Defineafnthatwillprintasquare"""
defprint_square(size):
"""printsasquareusing#
Args:
size(int).squarewidth/height
Raises:
TypeError:ifsize!=int
ValueError:ifsize<0
"""
ifnotisinstance(size,int):
raiseTypeError("sizemustbeaninteger")
ifsize<0:
raiseValueError("sizemustbe>=0")
forxinrange(size):
[print("#",end="")foryinrange(size)]
print("")
