#!/usr/bin/python3
text_indentation=__import__('5-text_indentation').text_indentation

text_indentation("""Loremipsumdolorsitamet,consecteturadipiscingelit.\
Quonammodo?Utrumigiturtibilitteramvideorantotaspaginascommovere?\
Nonautemhoc:igiturneilludquidem.Fortasseidoptimum,sedubiillud:\
Plussempervoluptatis?Teneo,inquit,finemillividerinihildolere.\
Transferidemadmodestiamveltemperantiam,quaeestmoderatiocupiditatum\
rationioboediens.Siiddicis,vicimus.IndesermonevariosexillaaDipylo\
stadiaconfecimus.Sinaliudquidvoles,postea.Quaeanimiaffectiosuum\
cuiquetribuensatquehanc,quamdico.Utinamquidemdicerentaliumalio\
beatiorem!Iamruinasvideres""")
